//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationGatekeeperAdmin.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colleague
    {
        public int ColleagueId { get; set; }
        public System.Guid GUID { get; set; }
        public string Username { get; set; }
        public string DisplayName { get; set; }
        public string JobTitle { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string LastFirstName { get; set; }
        public string Phone { get; set; }
        public string EMail { get; set; }
        public string Department { get; set; }
        public string Manager { get; set; }
        public string AlternatePhone { get; set; }
        public string DepartmentFloor { get; set; }
        public string Company { get; set; }
        public string DistinguishedName { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string MHCNumber { get; set; }
        public string MemberOf { get; set; }
        public bool Active { get; set; }
    }
}
