//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationGatekeeperAdmin.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogGatekeeper
    {
        public int LogId { get; set; }
        public Nullable<int> GatekeeperStatusId { get; set; }
        public string Note { get; set; }
        public Nullable<int> CernerPositionId { get; set; }
    
        public virtual CernerPosition CernerPosition { get; set; }
        public virtual GateKeeperStatu GateKeeperStatu { get; set; }
        public virtual Log Log { get; set; }
    }
}
