//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationGatekeeperAdmin.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Registration()
        {
            this.SystemIdentitys = new HashSet<SystemIdentity>();
            this.Logs = new HashSet<Log>();
        }
    
        public int RegistrationId { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public int OrganizationId { get; set; }
        public string OrganizationAbbreviation { get; set; }
        public int RelationshipId { get; set; }
        public string RelationshipName { get; set; }
        public string HREmployeeId { get; set; }
        public string HREmployeeEmail { get; set; }
        public string HRSupervisor { get; set; }
        public string HRCompany { get; set; }
        public string HRDepartment { get; set; }
        public string HRJobTitle { get; set; }
        public string ProviderNPI { get; set; }
        public Nullable<int> ProviderCredentialsId { get; set; }
        public string ProviderCredentialsName { get; set; }
        public string TitleExternal { get; set; }
        public string CompanyExternal { get; set; }
        public string CityExternal { get; set; }
        public string ContactNameExternal { get; set; }
        public string ContactPhoneExternal { get; set; }
        public Nullable<int> GatekeeperStatusId { get; set; }
        public string GatekeeperStatusName { get; set; }
        public Nullable<System.DateTime> GatekeeperValidatedDate { get; set; }
        public string GatekeeperUserId { get; set; }
        public string GatekeeperDisplayName { get; set; }
        public string GatekeeperNote { get; set; }
        public Nullable<int> CernerPositionId { get; set; }
        public string CernerPositionName { get; set; }
        public string VerifiedUserId { get; set; }
        public string ProviderSpecialty { get; set; }
        public Nullable<int> NursingAncillaryCredentialId { get; set; }
        public string NursingAncillaryCertification { get; set; }
    
        public virtual CernerPosition CernerPosition { get; set; }
        public virtual Credential Credential { get; set; }
        public virtual GateKeeperStatu GateKeeperStatu { get; set; }
        public virtual NursingAncillaryCredential NursingAncillaryCredential { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Relationship Relationship { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemIdentity> SystemIdentitys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Log> Logs { get; set; }
    }
}
