//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationGatekeeperAdmin.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemIdentity
    {
        public int SystemIdentityId { get; set; }
        public int RegistrationId { get; set; }
        public int SystemAccessId { get; set; }
        public int OrganizationId { get; set; }
        public string UserId { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual Registration Registration { get; set; }
        public virtual SystemAccess SystemAccess { get; set; }
    }
}
